== Règles de développement ==

Aujourd'hui qu'on utilise l'IA (Claude-code) pour développer, il est important de respecter des règles de développement strictes et absolues.

Surtout que pour le moment (juin 2026), les IA en sont incapables.

=== Approche fonctionnelle ===

L'approche doit être au maximum fonctionnelle,

=== Loi de Demeter absolue ===

On applique toujours la loi de Demeter absolue.

**Loi de Demeter simple**

Un objet, une classe, ne sait jamais comment un autre objet, une autre classe, fonctionne dans le détail. Seul l'objet, seule la classe, le sait.

**Loi de Demeter absolue**

Un objet lui-même ne sait pas comment il fait les choses. Par exemple, un Lister ne sait pas que pour cacher son propre panneau il ajoute la classe 'hidden' à  son container. Il ne connait "publiquement" que `this.hide()`


=== Fichiers _tdd ===

Emplacement canonique:: Emplacement du fichier lorsqu'il n'est pas "en cours" dans `_tdd`

Il existe :

- une version `specs/e2e/_tdd/` (test unitaires)
- une version `specs/unit/_tdd/ (test unitaires)

Afin de ne pas changer les imports dès qu'on déplace un module de tests (de son emplacement canonique au dossier _tdd et inversement)

Marque "//Origine: path"

marquer les tests `test.only` si on ne veut pas jouer l'intégralité


[[tdd-workflow]]
=== Fluw de travail TDD ===

SI Création d'un nouveau module

- Le créer provisoirement dans _tdd
- coder les tests

SINON

- Trouver le test à modifier en fonction du nouveau fonctionnement ou de la nouvelle fonctionnalité
- le déplacer dans `_tdd`
- bien vérifier que sa première ligne soit `//Origine: ...` sinon la définir
- `test.only` ou `test.skip` pour se concentrer si le ou les tests courants
- dire que c'est prêt.

QUAND tous les tests passent :

  - si c'est un nouveau 
    - lui choisir un emplacement canonique (MÊME HIÉRARCHIE)
    - mettre en commentaire en haut du fichier `//Origine: path/to/canonique`
  - retirer les `test.only` ou `test.skip` éventuels
  - (re)placer le fichier à sa place canonique sans rien faire d'autre
  - prévenir qu'on a fini



  avant même d'implémenter une fonction, se demander : 

  - est-elle propre à la classe
  - ou est-elle commune à presque toutes les clases

  .Distribution des responsabilité
  |====
  | Fonctionnalité propre à une classe
  | Fonctionnatilé utile  à toutes les classes

  | Exemples
  |

  | Ouverture du panneau des personnages
  | Ouverture de n'importe quel panneau

  | (donc traité par Lister)