#!/bin/bash
edcho ""
echo "1. Enter édite le brin — Not an input element (toHaveValue 'Mon brin')"
echo "   ./tests/specs/e2e/_tdd/brin-panel.spec.js:175"
echo ""
echo "2. Tab édition → badge — inactive (pas focusé)"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/brin-panel.spec.js:184"
echo ""
echo "3. Tab cycle complet — badge inactive"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/brin-panel.spec.js:193"
echo ""
echo "4. Tab cycle title→badge→type→color — badge inactive"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/brin-panel.spec.js:208"
echo ""
echo "5. brin persiste après rechargement — [data-field=\"badge\"] not found"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/brin-persistence.spec.js:47"
echo ""
echo "6. badge affiché après rechargement — [data-field=\"badge\"] not found"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/brin-persistence.spec.js:72"
echo ""
echo "7. brins cochés = brins de l'event — Expected /Brin [AB]/, Received \"Brin C\""
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/brins-selection.spec.js:107"
echo ""
echo "8. Alt+n crée brin AU-DESSUS — [data-field=\"title\"] not found"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/keyboard-alt-n.spec.js:103"
echo ""
echo "9. choisir dossier eventer.db → boîte confirmation — #projects-panel sans classe project-list (depuis :34)"
echo "   /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/open-existing-project.spec.js:13"
echo ""
echo "10. confirmer ouverture → projet dans liste — #projects-panel sans classe project-list (depuis :44)"
echo "    /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/open-existing-project.spec.js:13"
echo ""
echo "11. → sur projet ouvre events — #projects-panel sans classe project-list (depuis :59)"
echo "    /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/open-existing-project.spec.js:13"
echo ""
echo "12. annuler → aucun projet créé — #projects-panel sans classe project-list (depuis :75)"
echo "    /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/open-existing-project.spec.js:13"
echo ""
echo "13. ouverture projet existant → marques brins/persos — #events-panel sans classe event-list"
echo "    /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/open-existing-project.spec.js:98"
echo ""
echo "14. projet survit au rechargement — #projects-panel sans classe project-list (depuis :107)"
echo "    /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/open-existing-project.spec.js:13"
echo ""
echo "15. démarrage app — #projects-panel sans classe project-list"
echo "    /Users/philippeperret/Programmes/Eventer3/tests/specs/e2e/_tdd/start-up.spec.js:18"
echo ""
