== Filtrage ==

{appname} possède un système de filtrage puissant qui permet de filter très précisément les events pour les retrouver ou les grouper plus facilement. La touche magique du filtrage est combo:cmd+:[]. Elle permet d'entrer en mode filtre. La touche combo:tab[] permet ensuite de se déplacer de champ filtrable en champ filtrable.


==== Filtrer par le texte ====

C'est le premier filtrage qui est actité par la combinaison combo:cmd+:[].

[cols="1,4"]
|====
| **Action**      | **Attendu**
| combo:cmd+:[]   | Le listing courant passent en mode filtre +
Le curseur se place dans le champ au-dessus des textes.
|combo:a-z[]      | Les items apparaissent et disparaissent s'ils correspondent ou non au texte tapé.
|combo:cmd+:[]    | Sort de l'édition en gardant la liste filtrée. +
Pour sortir du filtrage en revenant à la liste initiale, taper combo:esc[].
|====




==== Cocher tous les filtrés ====

[cols="1,4"]
|====
| **Action**          | **Attendu**
| combo:maj+space[]   | Coche tous les éléments affichés
|====

