// Origine : tests/specs/e2e/brin/brin-reorder.spec.js
import { installFixtures } from '../../../helpers/install-fixtures.js'
import { test, expect, pane1, press } from '../__setup__.js'

test.describe('⌘+↑/↓ déplacement brins', () => {

  test.beforeEach(() => installFixtures('with-brins'))

  test('⌘+↓ déplace un brin vers le bas', async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'b')
    await pane1(page).locator('#brins-panel').waitFor()
    const items = pane1(page).locator('.brin-item')
    await expect(items.nth(0)).toContainText('Mon brin')
    await expect(items.nth(1)).toContainText('Autre brin')
    await press(page, 'Meta+ArrowDown')
    await expect(items.nth(0)).toContainText('Autre brin')
    await expect(items.nth(1)).toContainText('Mon brin')
  })

  test('⌘+↑ déplace un brin vers le haut', async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'b')
    await pane1(page).locator('#brins-panel').waitFor()
    const items = pane1(page).locator('.brin-item')
    await expect(items.nth(0)).toContainText('Mon brin')
    await expect(items.nth(1)).toContainText('Autre brin')
    await press(page, 'ArrowDown')
    await press(page, 'Meta+ArrowUp')
    await expect(items.nth(0)).toContainText('Autre brin')
    await expect(items.nth(1)).toContainText('Mon brin')
  })

  test("l'ordre après ⌘+↓ est persisté", async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'b')
    await pane1(page).locator('#brins-panel').waitFor()
    const items = pane1(page).locator('.brin-item')
    await expect(items.nth(0)).toContainText('Mon brin')
    await expect(items.nth(1)).toContainText('Autre brin')
    await press(page, 'Meta+ArrowDown')
    await expect(items.nth(0)).toContainText('Autre brin')
    await expect(items.nth(1)).toContainText('Mon brin')
    await page.waitForTimeout(500)
    await page.reload()
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'b')
    await pane1(page).locator('#brins-panel').waitFor()
    await expect(items.nth(0)).toContainText('Autre brin')
    await expect(items.nth(1)).toContainText('Mon brin')
  })

  test("l'ordre après ⌘+↑ est persisté", async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'b')
    await pane1(page).locator('#brins-panel').waitFor()
    const items = pane1(page).locator('.brin-item')
    await expect(items.nth(0)).toContainText('Mon brin')
    await expect(items.nth(1)).toContainText('Autre brin')
    await press(page, 'ArrowDown')
    await press(page, 'Meta+ArrowUp')
    await expect(items.nth(0)).toContainText('Autre brin')
    await expect(items.nth(1)).toContainText('Mon brin')
    await page.waitForTimeout(500)
    await page.reload()
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'b')
    await pane1(page).locator('#brins-panel').waitFor()
    await expect(items.nth(0)).toContainText('Autre brin')
    await expect(items.nth(1)).toContainText('Mon brin')
  })

})
