// Origine : tests/specs/e2e/perso/perso-reorder.spec.js
import { installFixtures } from '../../../helpers/install-fixtures.js'
import { test, expect, pane1, press } from '../__setup__.js'

test.describe('⌘+↑/↓ déplacement persos', () => {

  test.beforeEach(() => installFixtures('with-persos'))

  test('⌘+↓ déplace un perso vers le bas', async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'p')
    await pane1(page).locator('#persos-panel').waitFor()
    const items = pane1(page).locator('.perso-item')
    await expect(items.nth(0)).toContainText('Cyrano')
    await expect(items.nth(1)).toContainText('Roxane')
    await press(page, 'Meta+ArrowDown')
    await expect(items.nth(0)).toContainText('Roxane')
    await expect(items.nth(1)).toContainText('Cyrano')
  })

  test('⌘+↑ déplace un perso vers le haut', async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'p')
    await pane1(page).locator('#persos-panel').waitFor()
    const items = pane1(page).locator('.perso-item')
    await expect(items.nth(0)).toContainText('Cyrano')
    await expect(items.nth(1)).toContainText('Roxane')
    await press(page, 'ArrowDown')
    await press(page, 'Meta+ArrowUp')
    await expect(items.nth(0)).toContainText('Roxane')
    await expect(items.nth(1)).toContainText('Cyrano')
  })

  test("l'ordre après ⌘+↓ est persisté", async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'p')
    await pane1(page).locator('#persos-panel').waitFor()
    const items = pane1(page).locator('.perso-item')
    await expect(items.nth(0)).toContainText('Cyrano')
    await expect(items.nth(1)).toContainText('Roxane')
    await press(page, 'Meta+ArrowDown')
    await expect(items.nth(0)).toContainText('Roxane')
    await expect(items.nth(1)).toContainText('Cyrano')
    await page.waitForTimeout(500)
    await page.reload()
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'p')
    await pane1(page).locator('#persos-panel').waitFor()
    await expect(items.nth(0)).toContainText('Roxane')
    await expect(items.nth(1)).toContainText('Cyrano')
  })

  test("l'ordre après ⌘+↑ est persisté", async ({ page }) => {
    await page.goto('/')
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'p')
    await pane1(page).locator('#persos-panel').waitFor()
    const items = pane1(page).locator('.perso-item')
    await expect(items.nth(0)).toContainText('Cyrano')
    await expect(items.nth(1)).toContainText('Roxane')
    await press(page, 'ArrowDown')
    await press(page, 'Meta+ArrowUp')
    await expect(items.nth(0)).toContainText('Roxane')
    await expect(items.nth(1)).toContainText('Cyrano')
    await page.waitForTimeout(500)
    await page.reload()
    await pane1(page).locator('#projects-panel').waitFor()
    await press(page, 'ArrowRight')
    await pane1(page).locator('#events-panel').waitFor()
    await press(page, 'p')
    await pane1(page).locator('#persos-panel').waitFor()
    await expect(items.nth(0)).toContainText('Roxane')
    await expect(items.nth(1)).toContainText('Cyrano')
  })

})
